import { assetServerUrl } from '@/config';

export const assets = {
  logo: `${assetServerUrl}/assets/images/logo.svg`,
  google: `${assetServerUrl}/assets/images/google.svg`,
  shape1: `${assetServerUrl}/assets/images/shape1.svg`,
  shape2: `${assetServerUrl}/assets/images/shape2.svg`,
  shape3: `${assetServerUrl}/assets/images/shape3.svg`,
  darkShape: `${assetServerUrl}/assets/images/dark_shape.svg`,
  darkShape1: `${assetServerUrl}/assets/images/dark_shape1.svg`,
  darkShape2: `${assetServerUrl}/assets/images/dark_shape2.svg`,
  loginHero: `${assetServerUrl}/assets/images/login.png`,
  registrationHero: `${assetServerUrl}/assets/images/registration.png`,
  registrationHeroDark: `${assetServerUrl}/assets/images/registration1.png`,
  profileFallback: `${assetServerUrl}/assets/images/profile.png`,
  steveJobs: `${assetServerUrl}/assets/images/people1.png`,
  ryanRoslansky: `${assetServerUrl}/assets/images/people2.png`,
  dylanField: `${assetServerUrl}/assets/images/people3.png`,
  karimSaif: `${assetServerUrl}/assets/images/post_img.png`,
  radovanArena: `${assetServerUrl}/assets/images/txt_img.png`,
  genericAvatar: `${assetServerUrl}/assets/images/Avatar.png`,
  storyImg1: `${assetServerUrl}/assets/images/mobile_story_img.png`,
  storyImg2: `${assetServerUrl}/assets/images/mobile_story_img1.png`,
  storyImg3: `${assetServerUrl}/assets/images/mobile_story_img2.png`,
  storyImg4: `${assetServerUrl}/assets/images/mini_pic.png`,
  storyCardPpl1: `${assetServerUrl}/assets/images/card_ppl1.png`,
  storyCardPpl2: `${assetServerUrl}/assets/images/card_ppl2.png`,
  storyCardPpl3: `${assetServerUrl}/assets/images/card_ppl3.png`,
  storyCardPpl4: `${assetServerUrl}/assets/images/card_ppl4.png`,
  timelineImg: `${assetServerUrl}/assets/images/timeline_img.png`,
  feedEvent1: `${assetServerUrl}/assets/images/feed_event1.png`,
};
